// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/nizonglonggit/usercenter/internal/logic"
	"github.com/nizonglonggit/usercenter/internal/svc"
	"github.com/nizonglonggit/usercenter/usercenter"
)

type UserCenterServerServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserCenterServerServer(svcCtx *svc.ServiceContext) *UserCenterServerServer {
	return &UserCenterServerServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServerServer) RegisterUser(ctx context.Context, in *usercenter.RegisterUserReq) (*usercenter.BaseResp, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *UserCenterServerServer) Login(ctx context.Context, in *usercenter.LoginReq) (*usercenter.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
