// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./usercenterserver_mock.go -package usercenterserver -source $GOFILE

package usercenterserver

import (
	"context"

	"github.com/nizonglonggit/usercenter/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	BaseResp        = user.BaseResp
	RegisterUserReq = user.RegisterUserReq
	LoginReq        = user.LoginReq
	LoginResp       = user.LoginResp

	UserCenterServer interface {
		RegisterUser(ctx context.Context, in *RegisterUserReq) (*BaseResp, error)
		Login(ctx context.Context, in *LoginReq) (*LoginResp, error)
	}

	defaultUserCenterServer struct {
		cli zrpc.Client
	}
)

func NewUserCenterServer(cli zrpc.Client) UserCenterServer {
	return &defaultUserCenterServer{
		cli: cli,
	}
}

func (m *defaultUserCenterServer) RegisterUser(ctx context.Context, in *RegisterUserReq) (*BaseResp, error) {
	client := user.NewUserCenterServerClient(m.cli.Conn())
	return client.RegisterUser(ctx, in)
}

func (m *defaultUserCenterServer) Login(ctx context.Context, in *LoginReq) (*LoginResp, error) {
	client := user.NewUserCenterServerClient(m.cli.Conn())
	return client.Login(ctx, in)
}
